provisioning/roles/geospaas/tasks/main.yml
@mortenwh , can you look at it? Very simple fix ;)
=> #25 remove makemigrations in provisioning

geospaas/nansat_ingestor/managers.py, geospaas/nansat_ingestor/tests/tests.py, geospaas/vocabularies/managers.py, geospaas/vocabularies/tests.py, runtests.py
@mortenwh , can you look at this one also?
=> Hotfix26 ingestor metadata

geospaas/catalog/management/commands/count.py, geospaas/catalog/models.py, geospaas/catalog/tests.py, geospaas/nansat_ingestor/management/commands/ingest.py, geospaas/nansat_ingestor/managers.py, geospaas/nansat_ingestor/tests/tests.py, geospaas/tests.py, geospaas/utils/__init__.py, geospaas/utils/utils.py
=> Issue24 uri validation

.travis.yml, Dockerfile, README.md, build_container.sh, setup.py
Update Dockerfile and travis testing using docker
=> Issue43 docker

.travis.yml, Dockerfile, scripts/docker_push.sh
Fix for #71  @aperrin66, can you have a look? We am discuss on Monday if needed.
=> Issue71 travis docker

Dockerfile
=> add psycopg2 in the docker image

.travis.yml, setup.py
Trying to reopen PR to use the newest master
=> #75 added few line to travis for automatic deployment

geospaas/base_viewer/forms.py, geospaas/base_viewer/static/base_viewer/styles.css, geospaas/base_viewer/templates/base_viewer/elements.html, geospaas/base_viewer/tests.py, geospaas/base_viewer/views.py
* Add Paginator in Views
* Update templates to use page_obj
* Update tests
=> Fix #98 add Paginator

geospaas/base_viewer/static/base_viewer/js/base_viewer.js, geospaas/base_viewer/templates/base_viewer/elements.html, geospaas/base_viewer/tests.py, setup.py, tests/urls.py
* add ajax_url attribute to geometry_ref div in template with absolute url set by Django
* use attributes.ajax_url.value in JS
* add tests/ to test URLs
* update tests correspondingly
=> #99 set geometry url in template

geospaas/base_viewer/templates/base_viewer/elements.html, geospaas/base_viewer/templates/base_viewer/page_structure.html, geospaas/base_viewer/tests.py, geospaas/base_viewer/views.py, tests/settings.py
Fix #115 
* Replace links to previous/next page with buttons that trigger POST instead of GET
* Update paginator to use POST
* Update tests
=> Issue115 pagination

Dockerfile
Update Django to 3.06 and close #119
=> Pin Django 3.0.6

README.md
=> Issue124 docker doc

.travis.yml, Dockerfile, scripts/docker_push.sh
Closes #129 
Build a slim Docker image based on the nansat slim image.
FYI @aanersc
=> Slim Docker image

geospaas/base_viewer/templates/base_viewer/elements.html, geospaas/base_viewer/tests.py, geospaas/base_viewer/views.py, runtests.py, tests/settings.py
closes #135 
@akorosov @aperrin66 
The new feature of showing and hiding the local address is now configurable from the settings.py
=> Hotfix #135

geospaas/base_viewer/views.py
=> 140: exclude datasets without geographic_location

geospaas/base_viewer/static/base_viewer/js/base_viewer.js, geospaas/base_viewer/templates/base_viewer/elements.html, geospaas/base_viewer/templates/base_viewer/page_structure.html, geospaas/base_viewer/tests.py, tests/settings.py
Higligting of polygns with jquery
**NB:** 
This should be added to settings:
```
LEAFLET_CONFIG = {
'NO_GLOBALS': False,
}
``` 
Summary:
* Add jquery to template
* Use global maps
* Use jquery to add geojson polygons
* Use jquery to change polygon color on hover
* Simplify template: remove div.geometry_ref, add ajax_url to td.dataset_cell
=> #145 use jquery to highlight polygons

geospaas/base_viewer/forms.py, geospaas/base_viewer/static/base_viewer/styles.css, geospaas/base_viewer/templates/base_viewer/ds_info.html, geospaas/base_viewer/templates/base_viewer/elements.html
close #143 
close #150 
@aperrin66 @akorosov New viewer
It is also needed to make a version out of this new code as soon as possible because I need that for the deploy repository!
=> Issue#150 upgrading the viewer

.github/workflows/tests_build.yml, Dockerfile, geospaas/base_viewer/apps.py
Resolves #170 
- Update the nansat version
- Upgrade Django to version 3.2 in the Docker image
=> Upgrade to django 3.2

.github/workflows/tests_build.yml, .gitignore, geospaas/tests.py, geospaas/vocabularies/managers.py, geospaas/vocabularies/tests.py
Resolves #172 
There are several ways to deal with this.
The solution proposed here keeps the vocabulary models unchanged and maps the new GCMD fields to their old names.
We could also just add the new fields and have the old or new fields populated depending on the version of GCMD used (possible because models' fields are left blank when no value is found for them).
This would mean changing the database tables (migration) and adapting all existing code, which is why I preferred keeping the models unchanged.
=> Support new gcmd fields

setup.py
=> Update requirements in setup.py

.github/workflows/ci.yml, Dockerfile
Use pip instead of setup.py to install the geospaas package in the docker image.
=> Fix geospaas package installation in docker image
